import type { Metadata } from "next";
import { AuthProvider } from "@/lib/authContext";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"; // Import your Header component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthProvider>
					<Header /> {/* Render the Header here */}
					<main>{children}</main>{" "}
					{/* Your page content will be rendered here */}
				</AuthProvider>
			</body>
		</html>
	);
}
